// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package log represents the imported interface "rusm:runtime/log@0.1.0".
//
// Platform logging — a **polyfill** bridge. A guest's *standard* logging (`console.*`
// in
// TS, the `log` crate in Rust, `log`/`slog` in Go) routes here; the host stamps the
// time,
// the process's component name (its label) + pid, and the severity colour, formats
// it via
// `rusm-logfmt` exactly like every other RUSM line, and writes it to the node's log
// stream
// — gated by the node `[log] level`. Not capability-gated: it's operator-controlled
// diagnostics (an `off` node drops every line), so the guest wires no name/pid/format.
package log

import (
	"go.bytecodealliance.org/cm"
)

// LogLevel represents the enum "rusm:runtime/log@0.1.0#log-level".
//
// Severity — maps to `console.{error,warn,log/info,debug}` (TS) and the `log` crate's
// levels (Rust). `log`'s sub-debug `trace` folds into `debug`.
//
//	enum log-level {
//		error,
//		warn,
//		info,
//		debug
//	}
type LogLevel uint8

const (
	LogLevelError LogLevel = iota
	LogLevelWarn
	LogLevelInfo
	LogLevelDebug
)

var _LogLevelStrings = [4]string{
	"error",
	"warn",
	"info",
	"debug",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e LogLevel) String() string {
	return _LogLevelStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e LogLevel) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *LogLevel) UnmarshalText(text []byte) error {
	return _LogLevelUnmarshalCase(e, text)
}

var _LogLevelUnmarshalCase = cm.CaseUnmarshaler[LogLevel](_LogLevelStrings[:])

// Log represents the imported function "log".
//
// Emit one line through the platform logger; the guest supplies only severity + message.
//
//	log: func(level: log-level, message: string)
//
//go:nosplit
func Log(level LogLevel, message string) {
	level0 := (uint32)(level)
	message0, message1 := cm.LowerString(message)
	wasmimport_Log((uint32)(level0), (*uint8)(message0), (uint32)(message1))
	return
}
