// GENERATED by `rusm build` — do not edit. Ambient types for the app's custom bridges,
// so a TS guest calls them typed. Regenerated from bridges/ each build.

interface Query {
  city: string;
  units: Units;
}

interface Report {
  city: string;
  sky: Sky;
  temp: number;
}

type Sky = "Sunny" | "Cloudy" | "Rainy";

type Units = "Celsius" | "Fahrenheit";

declare const weather: {
  lookup(city: string): string;
  detailed(query: Query): Report;
};

