//! GENERATED by `rusm build` — do not edit. Mounts each custom bridge's host impl
//! and registers them all. Pass `extend` to `rusm_cli::host::serve`.

#[path = "../bridges/weather/host.rs"]
pub mod weather;

/// Register every custom application bridge into the component linker.
pub fn extend(linker: &mut rusm_wasm::BridgeLinker) -> rusm_wasm::wasmtime::Result<()> {
    weather::add_to_linker(linker)?;
    Ok(())
}
