//! GENERATED by `rusm build` — do not edit. Mounts each custom bridge's host impl
//! and registers them all. For pure-Rust-bridge apps pass `extend` to
//! `rusm_cli::host::serve`; for TS-bridge apps call `init` first via
//! `rusm_cli::host::serve_with_init`.

#[path = "../bridges/weather/host.rs"]
pub mod weather;

/// Register every custom application bridge into the component linker.
pub fn extend(linker: &mut rusm_wasm::BridgeLinker) -> rusm_wasm::wasmtime::Result<()> {
    weather::add_to_linker(linker)?;
    Ok(())
}
