// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package process represents the world "rusm:runtime/process@0.1.0".
//
// A RUSM actor component: imports the actor API and exports an entry point the
// runtime calls to start the process.
package process
