// Code generated by wit-bindgen-go. DO NOT EDIT.

package process

// Exports represents the caller-defined exports from "rusm:runtime/process@0.1.0".
var Exports struct {
	// Run represents the caller-defined, exported function "run".
	//
	//	run: func()
	Run func()
}
