// Code generated by wit-bindgen-go. DO NOT EDIT.

package process

// This file contains wasmimport and wasmexport declarations for "rusm:runtime@0.1.0".

//go:wasmexport run
//export run
func wasmexport_Run() {
	Exports.Run()
	return
}
