// Code generated by wit-bindgen-go. DO NOT EDIT.

package serve

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "rusm:runtime@0.1.0".

//go:wasmimport rusm:runtime/serve@0.1.0 connection
//go:noescape
func wasmimport_Connection(result *cm.Option[ConnectionInfo])

//go:wasmimport rusm:runtime/serve@0.1.0 ws-send-text
//go:noescape
func wasmimport_WsSendText(payload0 *uint8, payload1 uint32) (result0 uint32)

//go:wasmimport rusm:runtime/serve@0.1.0 ws-close
//go:noescape
func wasmimport_WsClose(code0 uint32, reason0 *uint8, reason1 uint32)

//go:wasmimport rusm:runtime/serve@0.1.0 sse-send
//go:noescape
func wasmimport_SseSend(data0 *uint8, data1 uint32, event0 uint32, event1 *uint8, event2 uint32, id0 uint32, id1 *uint8, id2 uint32, retry0 uint32, retry1 uint32) (result0 uint32)
