// A Go HTTP handler that calls the mailer bridge.
// `smtp` is generated by `rusm build` from bridges/mailer/bridge.wit.
package main

import (
	"github.com/archan937/rusm/packages/rusm-go/web"
	smtp "api/internal/wit/app/mailer/smtp"
)

type payload struct {
	To      string `json:"to"`
	Subject string `json:"subject"`
	Body    string `json:"body"`
}

func run() {
	h := web.NewHandlers()
	h.Handle("post", func(req web.Request, _ web.Params) web.Response {
		var p payload
		if err := req.JSON(&p); err != nil {
			return web.Status(400)
		}
		if smtp.Send(smtp.Message{To: p.To, Subject: p.Subject, Body: p.Body}) {
			return web.Status(202)
		}
		return web.Status(502)
	})
	h.Serve()
}
