// Code generated by wit-bindgen-go. DO NOT EDIT.

package streams

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "rusm:runtime@0.1.0".

//go:wasmimport rusm:runtime/streams@0.1.0 stream-open
//go:noescape
func wasmimport_StreamOpen(to0 uint64, result *cm.Option[StreamID])

//go:wasmimport rusm:runtime/streams@0.1.0 stream-write
//go:noescape
func wasmimport_StreamWrite(handle0 uint64, chunk0 *uint8, chunk1 uint32) (result0 uint32)

//go:wasmimport rusm:runtime/streams@0.1.0 stream-close
//go:noescape
func wasmimport_StreamClose(handle0 uint64)

//go:wasmimport rusm:runtime/streams@0.1.0 stream-accept
//go:noescape
func wasmimport_StreamAccept() (result0 uint64)

//go:wasmimport rusm:runtime/streams@0.1.0 stream-read
//go:noescape
func wasmimport_StreamRead(handle0 uint64, result *cm.Option[cm.List[uint8]])
