//! The app's **host binary** (the Option-1 custom-bridge model): it registers the app's
//! custom bridges, then serves the manifest — reusing `rusm_cli::host` so the serve loop is
//! identical to `rusm serve`. The only app-authored host file besides `bridges/<name>/`:
//! the rest (`bindings`/`bridges`/`wit`) is generated by `rusm build`.

mod bindings;
mod bridges;

use std::path::Path;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cfg =
        rusm_node::NodeConfig::load(Path::new("rusm.toml"), false).map_err(anyhow::Error::msg)?;
    // The single serve path, handed this app's bridge registrations. A pure-guest app would
    // pass `|_| Ok(())`; here we pass the generated `bridges::extend`.
    rusm_cli::host::serve(Path::new("."), &cfg, bridges::extend).await
}
