// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package actor represents the imported interface "rusm:runtime/actor@0.1.0".
//
// The actor / process API a RUSM component imports. Composition is by **message
// passing** — components address each other by pid and send bytes; there is no
// static component-to-component wiring and no lattice. A Rust guest binds this
// with `wit-bindgen` (a TS guest via the planned Bun + rquickjs shell, no jco);
// both call the same functions.
package actor

import (
	"go.bytecodealliance.org/cm"
)

// Pid represents the u64 "rusm:runtime/actor@0.1.0#pid".
//
// A process identifier (Erlang's pid).
//
//	type pid = u64
type Pid uint64

// ProcessInfo represents the record "rusm:runtime/actor@0.1.0#process-info".
//
// A snapshot of a process, mirroring the host's `Process.info`.
//
//	record process-info {
//		pid: pid,
//		links: u32,
//		monitors: u32,
//		names: list<string>,
//		label: option<string>,
//		mailbox-depth: u32,
//		trap-exit: bool,
//	}
type ProcessInfo struct {
	_            cm.HostLayout     `json:"-"`
	Pid          Pid               `json:"pid"`
	Links        uint32            `json:"links"`
	Monitors     uint32            `json:"monitors"`
	Names        cm.List[string]   `json:"names"`
	Label        cm.Option[string] `json:"label"`
	MailboxDepth uint32            `json:"mailbox-depth"`
	TrapExit     bool              `json:"trap-exit"`
}

// ConnectionInfo represents the record "rusm:runtime/actor@0.1.0#connection-info".
//
// The HTTP request context of a **per-connection serving process** — a WebSocket
// or
// SSE handler the host spawned for one accepted connection. Captured at accept time
// and fixed for the connection's life, so a handler reads it once in `open`.
//
//	record connection-info {
//		method: string,
//		path: string,
//		query: string,
//		params: list<tuple<string, string>>,
//		headers: list<tuple<string, string>>,
//		remote-addr: string,
//		subprotocol: option<string>,
//	}
type ConnectionInfo struct {
	_           cm.HostLayout      `json:"-"`
	Method      string             `json:"method"`
	Path        string             `json:"path"`
	Query       string             `json:"query"`
	Params      cm.List[[2]string] `json:"params"`
	Headers     cm.List[[2]string] `json:"headers"`
	RemoteAddr  string             `json:"remote-addr"`
	Subprotocol cm.Option[string]  `json:"subprotocol"`
}

// LogLevel represents the enum "rusm:runtime/actor@0.1.0#log-level".
//
// Severity for [`log`] — maps to `console.{error,warn,log/info,debug}` (TS) and the
// `log` crate's levels (Rust).
//
//	enum log-level {
//		error,
//		warn,
//		info,
//		debug
//	}
type LogLevel uint8

const (
	LogLevelError LogLevel = iota
	LogLevelWarn
	LogLevelInfo
	LogLevelDebug
)

var _LogLevelStrings = [4]string{
	"error",
	"warn",
	"info",
	"debug",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e LogLevel) String() string {
	return _LogLevelStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e LogLevel) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *LogLevel) UnmarshalText(text []byte) error {
	return _LogLevelUnmarshalCase(e, text)
}

var _LogLevelUnmarshalCase = cm.CaseUnmarshaler[LogLevel](_LogLevelStrings[:])

// SuperviseStrategy represents the enum "rusm:runtime/actor@0.1.0#supervise-strategy".
//
// A restart strategy for [`supervise`].
//
//	enum supervise-strategy {
//		one-for-one,
//		one-for-all,
//		rest-for-one
//	}
type SuperviseStrategy uint8

const (
	SuperviseStrategyOneForOne SuperviseStrategy = iota
	SuperviseStrategyOneForAll
	SuperviseStrategyRestForOne
)

var _SuperviseStrategyStrings = [3]string{
	"one-for-one",
	"one-for-all",
	"rest-for-one",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e SuperviseStrategy) String() string {
	return _SuperviseStrategyStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e SuperviseStrategy) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *SuperviseStrategy) UnmarshalText(text []byte) error {
	return _SuperviseStrategyUnmarshalCase(e, text)
}

var _SuperviseStrategyUnmarshalCase = cm.CaseUnmarshaler[SuperviseStrategy](_SuperviseStrategyStrings[:])

// StreamID represents the u64 "rusm:runtime/actor@0.1.0#stream-id".
//
// A handle to one byte stream this process owns (an id local to the process).
// (`stream` is a reserved WIT keyword, hence `stream-id`.)
//
//	type stream-id = u64
type StreamID uint64

// OwnPid represents the imported function "own-pid".
//
// This process's own pid (Erlang's `self()`).
//
//	own-pid: func() -> pid
//
//go:nosplit
func OwnPid() (result Pid) {
	result0 := wasmimport_OwnPid()
	result = (Pid)((uint64)(result0))
	return
}

// Connection represents the imported function "connection".
//
// This per-connection serving process's [`connection-info`], or `none` for every
// other process. Read it once in a WebSocket/SSE handler's `open`. Additive: a guest
// that never calls it is unaffected, and a non-connection process always gets `none`.
//
//	connection: func() -> option<connection-info>
//
//go:nosplit
func Connection() (result cm.Option[ConnectionInfo]) {
	wasmimport_Connection(&result)
	return
}

// Spawn represents the imported function "spawn".
//
// Spawn a registered component (by the name it was registered under) as a new
// process, returning its pid (Erlang's `spawn`). Capability-gated and
// **non-escalating**: the child inherits the spawner's capabilities, never
// more. `err` with a message if spawn is denied or the name is unknown.
//
//	spawn: func(component: string) -> result<pid, string>
//
//go:nosplit
func Spawn(component string) (result cm.Result[string, Pid, string]) {
	component0, component1 := cm.LowerString(component)
	wasmimport_Spawn((*uint8)(component0), (uint32)(component1), &result)
	return
}

// SpawnFrom represents the imported function "spawn-from".
//
// Spawn a **dynamic JS** instance of `component` — a node-declared *runner template*
// (a capability profile with no fixed bundle) — whose JS bundle is fetched at runtime
// from `source`: `url:<u>` / `http(s)://…`, or `kv:<bucket>/<key>` (the node's store).
// The instance runs under `component`'s **declared** profile (operator policy — the
// guest chooses the code, never the capabilities). Capability-gated: `spawn`, plus
// the
// spawner's own `network` (for a `url:` source) or `storage` (for `kv:`) — so a
// sandboxed guest can't drive arbitrary host fetches. `err` if denied, if `component`
// is not a dynamic template, or if the source can't be loaded.
//
//	spawn-from: func(component: string, source: string) -> result<pid, string>
//
//go:nosplit
func SpawnFrom(component string, source string) (result cm.Result[string, Pid, string]) {
	component0, component1 := cm.LowerString(component)
	source0, source1 := cm.LowerString(source)
	wasmimport_SpawnFrom((*uint8)(component0), (uint32)(component1), (*uint8)(source0), (uint32)(source1), &result)
	return
}

// Monitor represents the imported function "monitor".
//
// Monitor a process: when `target` dies, this process receives a `__down`
// message (Erlang's `monitor`) — the basis for a guest Supervisor.
//
//	monitor: func(target: pid)
//
//go:nosplit
func Monitor(target Pid) {
	target0 := (uint64)(target)
	wasmimport_Monitor((uint64)(target0))
	return
}

// Send represents the imported function "send".
//
// Send a byte message to another process; silently dropped if it's gone
// (like Erlang's `send`).
//
//	send: func(to: pid, message: list<u8>)
//
//go:nosplit
func Send(to Pid, message cm.List[uint8]) {
	to0 := (uint64)(to)
	message0, message1 := cm.LowerList(message)
	wasmimport_Send((uint64)(to0), (*uint8)(message0), (uint32)(message1))
	return
}

// Receive represents the imported function "receive".
//
// Receive the next message, suspending until one arrives (FIFO). The host
// runs this asynchronously, so a blocked guest frees its scheduler thread.
//
//	receive: func() -> list<u8>
//
//go:nosplit
func Receive() (result cm.List[uint8]) {
	wasmimport_Receive(&result)
	return
}

// ReceiveTimeout represents the imported function "receive-timeout".
//
// Like [`receive`], but gives up after `timeout-ms` and returns `none` —
// Erlang's `receive … after`. The basis for heartbeats and deadlines without
// a busy loop: wait for the next message *or* the timeout, whichever comes
// first. A monitored `__down` counts as a message (as it does for `receive`).
//
//	receive-timeout: func(timeout-ms: u64) -> option<list<u8>>
//
//go:nosplit
func ReceiveTimeout(timeoutMs uint64) (result cm.Option[cm.List[uint8]]) {
	timeoutMs0 := (uint64)(timeoutMs)
	wasmimport_ReceiveTimeout((uint64)(timeoutMs0), &result)
	return
}

// ListProcesses represents the imported function "list-processes".
//
// Every live pid (Erlang's `Process.list/0`).
//
//	list-processes: func() -> list<pid>
//
//go:nosplit
func ListProcesses() (result cm.List[Pid]) {
	wasmimport_ListProcesses(&result)
	return
}

// Info represents the imported function "info".
//
// A snapshot of a process (Erlang's `Process.info/1`), or none if it's gone.
//
//	info: func(target: pid) -> option<process-info>
//
//go:nosplit
func Info(target Pid) (result cm.Option[ProcessInfo]) {
	target0 := (uint64)(target)
	wasmimport_Info((uint64)(target0), &result)
	return
}

// IsAlive represents the imported function "is-alive".
//
// Whether a process is alive (`Process.alive?/1`).
//
//	is-alive: func(target: pid) -> bool
//
//go:nosplit
func IsAlive(target Pid) (result bool) {
	target0 := (uint64)(target)
	result0 := wasmimport_IsAlive((uint64)(target0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// Kill represents the imported function "kill".
//
// Kill a process (`Process.exit(pid, :kill)`). False if already gone.
//
//	kill: func(target: pid) -> bool
//
//go:nosplit
func Kill(target Pid) (result bool) {
	target0 := (uint64)(target)
	result0 := wasmimport_Kill((uint64)(target0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// Register represents the imported function "register".
//
// Register / look up / release a name in the node registry.
//
//	register: func(name: string) -> bool
//
//go:nosplit
func Register(name string) (result bool) {
	name0, name1 := cm.LowerString(name)
	result0 := wasmimport_Register((*uint8)(name0), (uint32)(name1))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// Whereis represents the imported function "whereis".
//
//	whereis: func(name: string) -> option<pid>
//
//go:nosplit
func Whereis(name string) (result cm.Option[Pid]) {
	name0, name1 := cm.LowerString(name)
	wasmimport_Whereis((*uint8)(name0), (uint32)(name1), &result)
	return
}

// Unregister represents the imported function "unregister".
//
//	unregister: func(name: string) -> bool
//
//go:nosplit
func Unregister(name string) (result bool) {
	name0, name1 := cm.LowerString(name)
	result0 := wasmimport_Unregister((*uint8)(name0), (uint32)(name1))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// SetLabel represents the imported function "set-label".
//
// Attach a human-readable label for observability (`Process.set_label/1`).
//
//	set-label: func(label: string)
//
//go:nosplit
func SetLabel(label string) {
	label0, label1 := cm.LowerString(label)
	wasmimport_SetLabel((*uint8)(label0), (uint32)(label1))
	return
}

// RegisterTag represents the imported function "register-tag".
//
// **Process-group tags** (Erlang's `pg`): join/leave **this** process (unprivileged),
// enumerate live members, and terminate a whole group. `kill-tag` is gated by
// process-control, like `kill`. Memberships release on exit.
//
//	register-tag: func(tag: string)
//
//go:nosplit
func RegisterTag(tag string) {
	tag0, tag1 := cm.LowerString(tag)
	wasmimport_RegisterTag((*uint8)(tag0), (uint32)(tag1))
	return
}

// UnregisterTag represents the imported function "unregister-tag".
//
//	unregister-tag: func(tag: string)
//
//go:nosplit
func UnregisterTag(tag string) {
	tag0, tag1 := cm.LowerString(tag)
	wasmimport_UnregisterTag((*uint8)(tag0), (uint32)(tag1))
	return
}

// WhereisTag represents the imported function "whereis-tag".
//
//	whereis-tag: func(tag: string) -> list<pid>
//
//go:nosplit
func WhereisTag(tag string) (result cm.List[Pid]) {
	tag0, tag1 := cm.LowerString(tag)
	wasmimport_WhereisTag((*uint8)(tag0), (uint32)(tag1), &result)
	return
}

// KillTag represents the imported function "kill-tag".
//
//	kill-tag: func(tag: string) -> u32
//
//go:nosplit
func KillTag(tag string) (result uint32) {
	tag0, tag1 := cm.LowerString(tag)
	result0 := wasmimport_KillTag((*uint8)(tag0), (uint32)(tag1))
	result = (uint32)((uint32)(result0))
	return
}

// Log represents the imported function "log".
//
// Emit a log line through the **platform** logger. The host stamps the timestamp,
// this process's component name (its label) + pid, and the severity colour, formats
// it exactly like every other RUSM log line, and writes it to the node's log stream
// —
// gated by the node's `[log] level`. The guest supplies only severity + message;
// name, pid, and format are the platform's, so a developer never wires them.
// `console.*` (TS) and the `log` crate (Rust) route here.
//
//	log: func(level: log-level, message: string)
//
//go:nosplit
func Log(level LogLevel, message string) {
	level0 := (uint32)(level)
	message0, message1 := cm.LowerString(message)
	wasmimport_Log((uint32)(level0), (*uint8)(message0), (uint32)(message1))
	return
}

// Supervise represents the imported function "supervise".
//
// Supervise named child components: restart a dead child per `strategy`, with a
// restart budget of at most `max-restarts` within `within-ms` (both `0` =
// unlimited / over the whole lifetime). Returns the supervisor's pid.
// Capability-gated like `spawn`; children inherit these capabilities, and the
// supervisor is linked to the caller — if it gives up (or the caller dies) the
// whole tree is torn down. This is the **one** restart implementation; the guest
// `Supervisor` SDKs delegate to it.
//
//	supervise: func(strategy: supervise-strategy, children: list<string>, max-restarts:
//	u32, within-ms: u32) -> result<pid, string>
//
//go:nosplit
func Supervise(strategy SuperviseStrategy, children cm.List[string], maxRestarts uint32, withinMs uint32) (result cm.Result[string, Pid, string]) {
	strategy0 := (uint32)(strategy)
	children0, children1 := cm.LowerList(children)
	maxRestarts0 := (uint32)(maxRestarts)
	withinMs0 := (uint32)(withinMs)
	wasmimport_Supervise((uint32)(strategy0), (*string)(children0), (uint32)(children1), (uint32)(maxRestarts0), (uint32)(withinMs0), &result)
	return
}

// StreamOpen represents the imported function "stream-open".
//
// Open a Tokio-backpressured byte stream to another process: the read end is
// delivered to `to` (it arrives via `stream-accept`), the write end is kept
// here under the returned handle. `none` if `to` is already gone.
//
//	stream-open: func(to: pid) -> option<stream-id>
//
//go:nosplit
func StreamOpen(to Pid) (result cm.Option[StreamID]) {
	to0 := (uint64)(to)
	wasmimport_StreamOpen((uint64)(to0), &result)
	return
}

// StreamWrite represents the imported function "stream-write".
//
// Write one chunk to a stream, suspending if the buffer is full (the reader
// applies natural back-pressure). `false` once the reader is gone / unknown id.
//
//	stream-write: func(handle: stream-id, chunk: list<u8>) -> bool
//
//go:nosplit
func StreamWrite(handle StreamID, chunk cm.List[uint8]) (result bool) {
	handle0 := (uint64)(handle)
	chunk0, chunk1 := cm.LowerList(chunk)
	result0 := wasmimport_StreamWrite((uint64)(handle0), (*uint8)(chunk0), (uint32)(chunk1))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// StreamClose represents the imported function "stream-close".
//
// Close the write end — the reader then sees end-of-stream.
//
//	stream-close: func(handle: stream-id)
//
//go:nosplit
func StreamClose(handle StreamID) {
	handle0 := (uint64)(handle)
	wasmimport_StreamClose((uint64)(handle0))
	return
}

// StreamAccept represents the imported function "stream-accept".
//
// Accept the next incoming byte stream, suspending until one arrives; returns
// a handle for reading it. (Like `receive`, plain messages are skipped here.)
//
//	stream-accept: func() -> stream-id
//
//go:nosplit
func StreamAccept() (result StreamID) {
	result0 := wasmimport_StreamAccept()
	result = (StreamID)((uint64)(result0))
	return
}

// StreamRead represents the imported function "stream-read".
//
// Read the next chunk from an accepted stream, suspending until one arrives.
// `none` at end-of-stream (the writer was closed/dropped).
//
//	stream-read: func(handle: stream-id) -> option<list<u8>>
//
//go:nosplit
func StreamRead(handle StreamID) (result cm.Option[cm.List[uint8]]) {
	handle0 := (uint64)(handle)
	wasmimport_StreamRead((uint64)(handle0), &result)
	return
}

// KvGet represents the imported function "kv-get".
//
// Durable key-value storage — a sub-capability of the actor surface (like
// `stream-*`), **gated by `storage`** (default-deny). Bytes in, bytes out,
// namespaced by `bucket`; backed by an embedded store the node owns (no external
// daemon). Each op `err`s with a message if storage is denied or unconfigured.
// The host application owns the store's file; a guest just names buckets + keys.
//
//	kv-get: func(bucket: string, key: string) -> result<option<list<u8>>, string>
//
//go:nosplit
func KvGet(bucket string, key string) (result cm.Result[OptionListU8Shape, cm.Option[cm.List[uint8]], string]) {
	bucket0, bucket1 := cm.LowerString(bucket)
	key0, key1 := cm.LowerString(key)
	wasmimport_KvGet((*uint8)(bucket0), (uint32)(bucket1), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// KvSet represents the imported function "kv-set".
//
//	kv-set: func(bucket: string, key: string, value: list<u8>) -> result<_, string>
//
//go:nosplit
func KvSet(bucket string, key string, value cm.List[uint8]) (result cm.Result[string, struct{}, string]) {
	bucket0, bucket1 := cm.LowerString(bucket)
	key0, key1 := cm.LowerString(key)
	value0, value1 := cm.LowerList(value)
	wasmimport_KvSet((*uint8)(bucket0), (uint32)(bucket1), (*uint8)(key0), (uint32)(key1), (*uint8)(value0), (uint32)(value1), &result)
	return
}

// KvDelete represents the imported function "kv-delete".
//
//	kv-delete: func(bucket: string, key: string) -> result<bool, string>
//
//go:nosplit
func KvDelete(bucket string, key string) (result cm.Result[string, bool, string]) {
	bucket0, bucket1 := cm.LowerString(bucket)
	key0, key1 := cm.LowerString(key)
	wasmimport_KvDelete((*uint8)(bucket0), (uint32)(bucket1), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// KvExists represents the imported function "kv-exists".
//
//	kv-exists: func(bucket: string, key: string) -> result<bool, string>
//
//go:nosplit
func KvExists(bucket string, key string) (result cm.Result[string, bool, string]) {
	bucket0, bucket1 := cm.LowerString(bucket)
	key0, key1 := cm.LowerString(key)
	wasmimport_KvExists((*uint8)(bucket0), (uint32)(bucket1), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// KvList represents the imported function "kv-list".
//
//	kv-list: func(bucket: string) -> result<list<string>, string>
//
//go:nosplit
func KvList(bucket string) (result cm.Result[cm.List[string], cm.List[string], string]) {
	bucket0, bucket1 := cm.LowerString(bucket)
	wasmimport_KvList((*uint8)(bucket0), (uint32)(bucket1), &result)
	return
}
