// Code generated by wit-bindgen-go. DO NOT EDIT.

package actor

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "rusm:runtime@0.1.0".

//go:wasmimport rusm:runtime/actor@0.1.0 own-pid
//go:noescape
func wasmimport_OwnPid() (result0 uint64)

//go:wasmimport rusm:runtime/actor@0.1.0 spawn
//go:noescape
func wasmimport_Spawn(component0 *uint8, component1 uint32, result *cm.Result[string, Pid, string])

//go:wasmimport rusm:runtime/actor@0.1.0 spawn-from
//go:noescape
func wasmimport_SpawnFrom(component0 *uint8, component1 uint32, source0 *uint8, source1 uint32, result *cm.Result[string, Pid, string])

//go:wasmimport rusm:runtime/actor@0.1.0 monitor
//go:noescape
func wasmimport_Monitor(target0 uint64)

//go:wasmimport rusm:runtime/actor@0.1.0 send
//go:noescape
func wasmimport_Send(to0 uint64, message0 *uint8, message1 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 receive
//go:noescape
func wasmimport_Receive(result *cm.List[uint8])

//go:wasmimport rusm:runtime/actor@0.1.0 receive-timeout
//go:noescape
func wasmimport_ReceiveTimeout(timeoutMs0 uint64, result *cm.Option[cm.List[uint8]])

//go:wasmimport rusm:runtime/actor@0.1.0 list-processes
//go:noescape
func wasmimport_ListProcesses(result *cm.List[Pid])

//go:wasmimport rusm:runtime/actor@0.1.0 info
//go:noescape
func wasmimport_Info(target0 uint64, result *cm.Option[ProcessInfo])

//go:wasmimport rusm:runtime/actor@0.1.0 is-alive
//go:noescape
func wasmimport_IsAlive(target0 uint64) (result0 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 kill
//go:noescape
func wasmimport_Kill(target0 uint64) (result0 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 register
//go:noescape
func wasmimport_Register(name0 *uint8, name1 uint32) (result0 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 whereis
//go:noescape
func wasmimport_Whereis(name0 *uint8, name1 uint32, result *cm.Option[Pid])

//go:wasmimport rusm:runtime/actor@0.1.0 unregister
//go:noescape
func wasmimport_Unregister(name0 *uint8, name1 uint32) (result0 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 set-label
//go:noescape
func wasmimport_SetLabel(label0 *uint8, label1 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 register-tag
//go:noescape
func wasmimport_RegisterTag(tag0 *uint8, tag1 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 unregister-tag
//go:noescape
func wasmimport_UnregisterTag(tag0 *uint8, tag1 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 whereis-tag
//go:noescape
func wasmimport_WhereisTag(tag0 *uint8, tag1 uint32, result *cm.List[Pid])

//go:wasmimport rusm:runtime/actor@0.1.0 kill-tag
//go:noescape
func wasmimport_KillTag(tag0 *uint8, tag1 uint32) (result0 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 log
//go:noescape
func wasmimport_Log(level0 uint32, message0 *uint8, message1 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 supervise
//go:noescape
func wasmimport_Supervise(strategy0 uint32, children0 *string, children1 uint32, maxRestarts0 uint32, withinMs0 uint32, result *cm.Result[string, Pid, string])

//go:wasmimport rusm:runtime/actor@0.1.0 stream-open
//go:noescape
func wasmimport_StreamOpen(to0 uint64, result *cm.Option[StreamID])

//go:wasmimport rusm:runtime/actor@0.1.0 stream-write
//go:noescape
func wasmimport_StreamWrite(handle0 uint64, chunk0 *uint8, chunk1 uint32) (result0 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 stream-close
//go:noescape
func wasmimport_StreamClose(handle0 uint64)

//go:wasmimport rusm:runtime/actor@0.1.0 stream-accept
//go:noescape
func wasmimport_StreamAccept() (result0 uint64)

//go:wasmimport rusm:runtime/actor@0.1.0 stream-read
//go:noescape
func wasmimport_StreamRead(handle0 uint64, result *cm.Option[cm.List[uint8]])

//go:wasmimport rusm:runtime/actor@0.1.0 kv-get
//go:noescape
func wasmimport_KvGet(bucket0 *uint8, bucket1 uint32, key0 *uint8, key1 uint32, result *cm.Result[OptionListU8Shape, cm.Option[cm.List[uint8]], string])

//go:wasmimport rusm:runtime/actor@0.1.0 kv-set
//go:noescape
func wasmimport_KvSet(bucket0 *uint8, bucket1 uint32, key0 *uint8, key1 uint32, value0 *uint8, value1 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport rusm:runtime/actor@0.1.0 kv-delete
//go:noescape
func wasmimport_KvDelete(bucket0 *uint8, bucket1 uint32, key0 *uint8, key1 uint32, result *cm.Result[string, bool, string])

//go:wasmimport rusm:runtime/actor@0.1.0 kv-exists
//go:noescape
func wasmimport_KvExists(bucket0 *uint8, bucket1 uint32, key0 *uint8, key1 uint32, result *cm.Result[string, bool, string])

//go:wasmimport rusm:runtime/actor@0.1.0 kv-list
//go:noescape
func wasmimport_KvList(bucket0 *uint8, bucket1 uint32, result *cm.Result[cm.List[string], cm.List[string], string])
