// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package actor represents the imported interface "rusm:runtime/actor@0.1.0".
package actor

import (
	"github.com/archan937/rusm/packages/rusm-go/internal/wit/rusm/runtime/types"
	"go.bytecodealliance.org/cm"
)

// Pid represents the type alias "rusm:runtime/actor@0.1.0#pid".
//
// See [types.Pid] for more information.
type Pid = types.Pid

// ProcessInfo represents the record "rusm:runtime/actor@0.1.0#process-info".
//
// A snapshot of a process, mirroring the host's `Process.info`.
//
//	record process-info {
//		pid: pid,
//		links: u32,
//		monitors: u32,
//		names: list<string>,
//		label: option<string>,
//		mailbox-depth: u32,
//		trap-exit: bool,
//	}
type ProcessInfo struct {
	_            cm.HostLayout     `json:"-"`
	Pid          Pid               `json:"pid"`
	Links        uint32            `json:"links"`
	Monitors     uint32            `json:"monitors"`
	Names        cm.List[string]   `json:"names"`
	Label        cm.Option[string] `json:"label"`
	MailboxDepth uint32            `json:"mailbox-depth"`
	TrapExit     bool              `json:"trap-exit"`
}

// SuperviseStrategy represents the enum "rusm:runtime/actor@0.1.0#supervise-strategy".
//
// A restart strategy for [`supervise`].
//
//	enum supervise-strategy {
//		one-for-one,
//		one-for-all,
//		rest-for-one
//	}
type SuperviseStrategy uint8

const (
	SuperviseStrategyOneForOne SuperviseStrategy = iota
	SuperviseStrategyOneForAll
	SuperviseStrategyRestForOne
)

var _SuperviseStrategyStrings = [3]string{
	"one-for-one",
	"one-for-all",
	"rest-for-one",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e SuperviseStrategy) String() string {
	return _SuperviseStrategyStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e SuperviseStrategy) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *SuperviseStrategy) UnmarshalText(text []byte) error {
	return _SuperviseStrategyUnmarshalCase(e, text)
}

var _SuperviseStrategyUnmarshalCase = cm.CaseUnmarshaler[SuperviseStrategy](_SuperviseStrategyStrings[:])

// OwnPid represents the imported function "own-pid".
//
// This process's own pid (Erlang's `self()`).
//
//	own-pid: func() -> pid
//
//go:nosplit
func OwnPid() (result Pid) {
	result0 := wasmimport_OwnPid()
	result = (types.Pid)((uint64)(result0))
	return
}

// Spawn represents the imported function "spawn".
//
// Spawn a registered component (by the name it was registered under) as a new
// process, returning its pid (Erlang's `spawn`). Capability-gated and
// **non-escalating**: the child inherits the spawner's capabilities, never
// more. `err` with a message if spawn is denied or the name is unknown.
//
//	spawn: func(component: string) -> result<pid, string>
//
//go:nosplit
func Spawn(component string) (result cm.Result[string, Pid, string]) {
	component0, component1 := cm.LowerString(component)
	wasmimport_Spawn((*uint8)(component0), (uint32)(component1), &result)
	return
}

// SpawnFrom represents the imported function "spawn-from".
//
// Spawn a **dynamic JS** instance of `component` — a node-declared *runner template*
// (a capability profile with no fixed bundle) — whose JS bundle is fetched at runtime
// from `source`: `url:<u>` / `http(s)://…`, or `kv:<bucket>/<key>` (the node's store).
// The instance runs under `component`'s **declared** profile (operator policy — the
// guest chooses the code, never the capabilities). Capability-gated: `spawn`, plus
// the
// spawner's own `network` (for a `url:` source) or `storage` (for `kv:`) — so a
// sandboxed guest can't drive arbitrary host fetches. `err` if denied, if `component`
// is not a dynamic template, or if the source can't be loaded.
//
//	spawn-from: func(component: string, source: string) -> result<pid, string>
//
//go:nosplit
func SpawnFrom(component string, source string) (result cm.Result[string, Pid, string]) {
	component0, component1 := cm.LowerString(component)
	source0, source1 := cm.LowerString(source)
	wasmimport_SpawnFrom((*uint8)(component0), (uint32)(component1), (*uint8)(source0), (uint32)(source1), &result)
	return
}

// Monitor represents the imported function "monitor".
//
// Monitor a process: when `target` dies, this process receives a `__down`
// message (Erlang's `monitor`) — the basis for a guest Supervisor.
//
//	monitor: func(target: pid)
//
//go:nosplit
func Monitor(target Pid) {
	target0 := (uint64)(target)
	wasmimport_Monitor((uint64)(target0))
	return
}

// Send represents the imported function "send".
//
// Send a byte message to another process; silently dropped if it's gone
// (like Erlang's `send`).
//
//	send: func(to: pid, message: list<u8>)
//
//go:nosplit
func Send(to Pid, message cm.List[uint8]) {
	to0 := (uint64)(to)
	message0, message1 := cm.LowerList(message)
	wasmimport_Send((uint64)(to0), (*uint8)(message0), (uint32)(message1))
	return
}

// Receive represents the imported function "receive".
//
// Receive the next message, suspending until one arrives (FIFO). The host
// runs this asynchronously, so a blocked guest frees its scheduler thread.
//
//	receive: func() -> list<u8>
//
//go:nosplit
func Receive() (result cm.List[uint8]) {
	wasmimport_Receive(&result)
	return
}

// ReceiveTimeout represents the imported function "receive-timeout".
//
// Like [`receive`], but gives up after `timeout-ms` and returns `none` —
// Erlang's `receive … after`. The basis for heartbeats and deadlines without
// a busy loop: wait for the next message *or* the timeout, whichever comes
// first. A monitored `__down` counts as a message (as it does for `receive`).
//
//	receive-timeout: func(timeout-ms: u64) -> option<list<u8>>
//
//go:nosplit
func ReceiveTimeout(timeoutMs uint64) (result cm.Option[cm.List[uint8]]) {
	timeoutMs0 := (uint64)(timeoutMs)
	wasmimport_ReceiveTimeout((uint64)(timeoutMs0), &result)
	return
}

// ListProcesses represents the imported function "list-processes".
//
// Every live pid (Erlang's `Process.list/0`).
//
//	list-processes: func() -> list<pid>
//
//go:nosplit
func ListProcesses() (result cm.List[Pid]) {
	wasmimport_ListProcesses(&result)
	return
}

// Info represents the imported function "info".
//
// A snapshot of a process (Erlang's `Process.info/1`), or none if it's gone.
//
//	info: func(target: pid) -> option<process-info>
//
//go:nosplit
func Info(target Pid) (result cm.Option[ProcessInfo]) {
	target0 := (uint64)(target)
	wasmimport_Info((uint64)(target0), &result)
	return
}

// IsAlive represents the imported function "is-alive".
//
// Whether a process is alive (`Process.alive?/1`).
//
//	is-alive: func(target: pid) -> bool
//
//go:nosplit
func IsAlive(target Pid) (result bool) {
	target0 := (uint64)(target)
	result0 := wasmimport_IsAlive((uint64)(target0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// Kill represents the imported function "kill".
//
// Kill a process (`Process.exit(pid, :kill)`). False if already gone.
//
//	kill: func(target: pid) -> bool
//
//go:nosplit
func Kill(target Pid) (result bool) {
	target0 := (uint64)(target)
	result0 := wasmimport_Kill((uint64)(target0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// Register represents the imported function "register".
//
// Register / look up / release a name in the node registry.
//
//	register: func(name: string) -> bool
//
//go:nosplit
func Register(name string) (result bool) {
	name0, name1 := cm.LowerString(name)
	result0 := wasmimport_Register((*uint8)(name0), (uint32)(name1))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// Whereis represents the imported function "whereis".
//
//	whereis: func(name: string) -> option<pid>
//
//go:nosplit
func Whereis(name string) (result cm.Option[Pid]) {
	name0, name1 := cm.LowerString(name)
	wasmimport_Whereis((*uint8)(name0), (uint32)(name1), &result)
	return
}

// Unregister represents the imported function "unregister".
//
//	unregister: func(name: string) -> bool
//
//go:nosplit
func Unregister(name string) (result bool) {
	name0, name1 := cm.LowerString(name)
	result0 := wasmimport_Unregister((*uint8)(name0), (uint32)(name1))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// SetLabel represents the imported function "set-label".
//
// Attach a human-readable label for observability (`Process.set_label/1`).
//
//	set-label: func(label: string)
//
//go:nosplit
func SetLabel(label string) {
	label0, label1 := cm.LowerString(label)
	wasmimport_SetLabel((*uint8)(label0), (uint32)(label1))
	return
}

// Supervise represents the imported function "supervise".
//
// Supervise named child components: restart a dead child per `strategy`, with a
// restart budget of at most `max-restarts` within `within-ms` (both `0` =
// unlimited / over the whole lifetime). Returns the supervisor's pid.
// Capability-gated like `spawn`; children inherit these capabilities, and the
// supervisor is linked to the caller — if it gives up (or the caller dies) the
// whole tree is torn down. This is the **one** restart implementation; the guest
// `Supervisor` SDKs delegate to it.
//
//	supervise: func(strategy: supervise-strategy, children: list<string>, max-restarts:
//	u32, within-ms: u32) -> result<pid, string>
//
//go:nosplit
func Supervise(strategy SuperviseStrategy, children cm.List[string], maxRestarts uint32, withinMs uint32) (result cm.Result[string, Pid, string]) {
	strategy0 := (uint32)(strategy)
	children0, children1 := cm.LowerList(children)
	maxRestarts0 := (uint32)(maxRestarts)
	withinMs0 := (uint32)(withinMs)
	wasmimport_Supervise((uint32)(strategy0), (*string)(children0), (uint32)(children1), (uint32)(maxRestarts0), (uint32)(withinMs0), &result)
	return
}

// SendAfter represents the imported function "send-after".
//
// Schedule `message` to be delivered to `to` after `delay-ms` milliseconds
// (Erlang's `erlang:send_after/3`). Returns a timer handle for [`cancel-timer`].
// If `to` is already gone when the timer fires, the delivery is a silent no-op —
// exactly like [`send`]. No capability gate beyond what the caller already holds:
// a process may schedule delayed messages to any pid it could send to directly.
//
//	send-after: func(to: pid, delay-ms: u64, message: list<u8>) -> u64
//
//go:nosplit
func SendAfter(to Pid, delayMs uint64, message cm.List[uint8]) (result uint64) {
	to0 := (uint64)(to)
	delayMs0 := (uint64)(delayMs)
	message0, message1 := cm.LowerList(message)
	result0 := wasmimport_SendAfter((uint64)(to0), (uint64)(delayMs0), (*uint8)(message0), (uint32)(message1))
	result = (uint64)((uint64)(result0))
	return
}

// CancelTimer represents the imported function "cancel-timer".
//
// Cancel a pending timer by the handle returned by [`send-after`]. Returns `true`
// if the timer was found and aborted before it fired; `false` if the handle is
// unknown — already fired, already cancelled, or never issued by this process.
//
//	cancel-timer: func(timer-ref: u64) -> bool
//
//go:nosplit
func CancelTimer(timerRef uint64) (result bool) {
	timerRef0 := (uint64)(timerRef)
	result0 := wasmimport_CancelTimer((uint64)(timerRef0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}
