// Code generated by wit-bindgen-go. DO NOT EDIT.

package actor

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "rusm:runtime@0.1.0".

//go:wasmimport rusm:runtime/actor@0.1.0 own-pid
//go:noescape
func wasmimport_OwnPid() (result0 uint64)

//go:wasmimport rusm:runtime/actor@0.1.0 spawn
//go:noescape
func wasmimport_Spawn(component0 *uint8, component1 uint32, result *cm.Result[string, Pid, string])

//go:wasmimport rusm:runtime/actor@0.1.0 spawn-from
//go:noescape
func wasmimport_SpawnFrom(component0 *uint8, component1 uint32, source0 *uint8, source1 uint32, result *cm.Result[string, Pid, string])

//go:wasmimport rusm:runtime/actor@0.1.0 monitor
//go:noescape
func wasmimport_Monitor(target0 uint64)

//go:wasmimport rusm:runtime/actor@0.1.0 send
//go:noescape
func wasmimport_Send(to0 uint64, message0 *uint8, message1 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 receive
//go:noescape
func wasmimport_Receive(result *cm.List[uint8])

//go:wasmimport rusm:runtime/actor@0.1.0 receive-timeout
//go:noescape
func wasmimport_ReceiveTimeout(timeoutMs0 uint64, result *cm.Option[cm.List[uint8]])

//go:wasmimport rusm:runtime/actor@0.1.0 stash
//go:noescape
func wasmimport_Stash(message0 *uint8, message1 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 unstash
//go:noescape
func wasmimport_Unstash()

//go:wasmimport rusm:runtime/actor@0.1.0 list-processes
//go:noescape
func wasmimport_ListProcesses(result *cm.List[Pid])

//go:wasmimport rusm:runtime/actor@0.1.0 info
//go:noescape
func wasmimport_Info(target0 uint64, result *cm.Option[ProcessInfo])

//go:wasmimport rusm:runtime/actor@0.1.0 is-alive
//go:noescape
func wasmimport_IsAlive(target0 uint64) (result0 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 kill
//go:noescape
func wasmimport_Kill(target0 uint64) (result0 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 register
//go:noescape
func wasmimport_Register(name0 *uint8, name1 uint32) (result0 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 whereis
//go:noescape
func wasmimport_Whereis(name0 *uint8, name1 uint32, result *cm.Option[Pid])

//go:wasmimport rusm:runtime/actor@0.1.0 unregister
//go:noescape
func wasmimport_Unregister(name0 *uint8, name1 uint32) (result0 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 set-label
//go:noescape
func wasmimport_SetLabel(label0 *uint8, label1 uint32)

//go:wasmimport rusm:runtime/actor@0.1.0 supervise
//go:noescape
func wasmimport_Supervise(strategy0 uint32, children0 *string, children1 uint32, maxRestarts0 uint32, withinMs0 uint32, result *cm.Result[string, Pid, string])

//go:wasmimport rusm:runtime/actor@0.1.0 send-after
//go:noescape
func wasmimport_SendAfter(to0 uint64, delayMs0 uint64, message0 *uint8, message1 uint32) (result0 uint64)

//go:wasmimport rusm:runtime/actor@0.1.0 cancel-timer
//go:noescape
func wasmimport_CancelTimer(timerRef0 uint64) (result0 uint32)
