//! `rusm new <name> --template todo-board --lang ts|rust|go` — scaffold the full
//! collaborative todo board (HTTP CRUD + a live SSE feed + WebSocket chat + a service
//! driven by a worker), the same app the `examples/<lang>/` directories hold.
//!
//! **Single source of truth, with a vendored copy.** The scaffold contents ARE the real
//! example files — but `cargo publish` only packages files *inside* this crate, so the
//! curated example tree is vendored under `rusm-cli/templates/<lang>/` and embedded from
//! there with `include_str!` (embedding straight from `../examples/` would compile in-repo
//! but break the published crate, where `examples/` isn't in the tarball). `templates/` is
//! a verbatim copy of the curated `examples/<lang>` files, regenerated by `make
//! sync-templates`; two tests guard it — the embedded set must match the on-disk example,
//! and each vendored file must be byte-identical to its `examples/` original — so the copy
//! can never silently drift. The one thing a standalone scaffolded app must differ in is
//! its dependency manifests: the examples use repo-local path/`replace` deps (they live in
//! this tree), so those are rewritten to published references on the way out.

use anyhow::{bail, Result};
use std::path::PathBuf;

use crate::scaffold::{package_json, Lang, SDK_VERSION};

/// The template to scaffold. `TodoBoard` is the full multi-protocol app; `Weather` is the
/// custom-bridge example (a native `weather` host function called from the guest); `Mailer`
/// is a TS-hosted bridge that sends transactional email via Resend. The `Weather` and
/// `Mailer` files come from the bridge scaffolder (`crate::scaffold::bridge_files` /
/// `mailer_bridge_files`), not this module, so neither is listed in `files()` below.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Template {
    TodoBoard,
    Weather,
    Mailer,
}

/// Parse the `--template` value.
pub fn parse_template(value: &str) -> Result<Template> {
    match value {
        "todo-board" | "todo" | "board" => Ok(Template::TodoBoard),
        "weather" | "bridge" | "custom-bridge" => Ok(Template::Weather),
        "mailer" | "email" => Ok(Template::Mailer),
        other => bail!(
            "unknown template `{other}` — templates are `todo-board`, `weather`, and `mailer`"
        ),
    }
}

/// `(relative path within the app, file contents)` for one example file, embedded from the
/// vendored `rusm-cli/templates/<lang>/<path>` copy at build time (kept identical to
/// `examples/<lang>/<path>` by `make sync-templates` and the guard tests below).
macro_rules! embed {
    ($lang:literal, $($path:literal),+ $(,)?) => {
        &[ $( ($path, include_str!(concat!("../templates/", $lang, "/", $path))) ),+ ]
    };
}

type Files = &'static [(&'static str, &'static str)];

// The embedded example trees, minus build artifacts (wasm/, node_modules, *.lock, go.sum)
// and minus files this module *generates* (the TS package.json — it carries the dep refs).
const TS_FILES: Files = embed!(
    "typescript",
    "rusm.toml",
    ".gitignore",
    "README.md",
    "tsconfig.json",
    "lib/todos.ts",
    "lib/page.ts",
    "components/api/index.ts",
    "components/api/index.test.ts",
    "components/chat/index.ts",
    "components/chat/index.test.ts",
    "components/feed/index.ts",
    "components/feed/index.test.ts",
    "components/reporter/index.ts",
    "components/reporter/index.test.ts",
    "components/store/index.ts",
    "components/store/index.test.ts",
);

// The Rust app's manifests are vendored as `Cargo.toml.tmpl`, not `Cargo.toml`: `cargo
// publish` treats any subdirectory holding a literal `Cargo.toml` as a nested package and
// drops it from the tarball, so the suffix keeps them as plain data. `files()` strips
// `.tmpl` back to `Cargo.toml` on the way into a scaffolded app.
const RS_FILES: Files = embed!(
    "rust",
    "rusm.toml",
    ".gitignore",
    "README.md",
    "todos/Cargo.toml.tmpl",
    "todos/src/lib.rs",
    "store-svc/Cargo.toml.tmpl",
    "store-svc/src/lib.rs",
    "components/api/Cargo.toml.tmpl",
    "components/api/page.html",
    "components/api/src/lib.rs",
    "components/chat/Cargo.toml.tmpl",
    "components/chat/src/lib.rs",
    "components/feed/Cargo.toml.tmpl",
    "components/feed/src/lib.rs",
    "components/reporter/Cargo.toml.tmpl",
    "components/reporter/src/lib.rs",
    "components/store/Cargo.toml.tmpl",
    "components/store/src/lib.rs",
);

const GO_FILES: Files = embed!(
    "go",
    "rusm.toml",
    ".gitignore",
    "README.md",
    "shared/go.mod",
    "shared/todos/todos.go",
    "shared/store/store.go",
    "components/api/go.mod",
    "components/api/main.go",
    "components/api/page.html",
    "components/chat/go.mod",
    "components/chat/main.go",
    "components/feed/go.mod",
    "components/feed/main.go",
    "components/reporter/go.mod",
    "components/reporter/main.go",
    "components/store/go.mod",
    "components/store/main.go",
);

/// The full file set for a template app: the embedded example, with manifests rewritten to
/// published dependency references and (for TS) a generated `package.json`.
pub fn files(lang: Lang, name: &str) -> Vec<(PathBuf, String)> {
    let raw: Files = match lang {
        Lang::TypeScript => TS_FILES,
        Lang::Rust => RS_FILES,
        Lang::Go => GO_FILES,
        // Templates require a real guest language; `parse_new_args` rejects `generic`.
        Lang::Generic => &[],
    };

    let mut out: Vec<(PathBuf, String)> = raw
        .iter()
        .map(|(rel, content)| {
            // The vendored Rust manifests are stored as `Cargo.toml.tmpl`; a scaffolded app
            // gets a real `Cargo.toml`.
            let out_path = rel.strip_suffix(".tmpl").unwrap_or(rel);
            let contents = if out_path.ends_with("Cargo.toml") {
                publishify_cargo(content)
            } else if out_path.ends_with("go.mod") {
                publishify_gomod(content)
            } else {
                (*content).to_string()
            };
            (PathBuf::from(out_path), contents)
        })
        .collect();

    if lang == Lang::TypeScript {
        out.push((PathBuf::from("package.json"), package_json(name)));
    }
    out
}

/// Rewrite the repo-local `rusm-rs` path dependency to the published crate; intra-app path
/// deps (`todos`, `store-svc`) are left as-is — they're correct in a standalone app.
fn publishify_cargo(src: &str) -> String {
    let mut out = String::with_capacity(src.len());
    for line in src.lines() {
        if line.trim_start().starts_with("rusm-rs = { path") {
            out.push_str(&format!("rusm-rs = \"{SDK_VERSION}\""));
        } else {
            out.push_str(line);
        }
        out.push('\n');
    }
    out
}

/// Rewrite a `go.mod`: drop the repo-local `rusm-go` `replace` and pin the published
/// version; the intra-app `replace todoboard => ...` stays. Collapses the blank line the
/// dropped `replace` would leave behind.
fn publishify_gomod(src: &str) -> String {
    let kept: Vec<String> = src
        .lines()
        .filter(|line| {
            !line
                .trim_start()
                .starts_with("replace github.com/archan937/rusm/packages/rusm-go =>")
        })
        .map(|line| {
            line.replace(
                "github.com/archan937/rusm/packages/rusm-go v0.0.0",
                &format!("github.com/archan937/rusm/packages/rusm-go v{SDK_VERSION}"),
            )
        })
        .collect();

    // Collapse any blank-line run (the dropped `replace` can leave a double blank) and
    // trim trailing blanks, so the output is clean without needing `go mod tidy`.
    let mut out = String::with_capacity(src.len());
    let mut prev_blank = false;
    for line in kept.iter().map(|l| l.as_str()) {
        let blank = line.trim().is_empty();
        if blank && prev_blank {
            continue;
        }
        out.push_str(line);
        out.push('\n');
        prev_blank = blank;
    }
    while out.ends_with("\n\n") {
        out.pop();
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;
    use std::path::Path;

    /// Every source file of `examples/todo-board/<lang>` (minus build artifacts and the files
    /// this module generates), as app-relative paths.
    fn on_disk_sources(lang: &str, generated: &[&str]) -> BTreeSet<String> {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("examples")
            .join("todo-board")
            .join(lang);
        let mut set = BTreeSet::new();
        collect(&root, &root, &mut set);
        for g in generated {
            set.remove(*g);
        }
        set
    }

    fn collect(base: &Path, dir: &Path, out: &mut BTreeSet<String>) {
        for entry in std::fs::read_dir(dir).unwrap() {
            let path = entry.unwrap().path();
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            if path.is_dir() {
                if !matches!(name.as_str(), "target" | "node_modules" | "wasm") {
                    collect(base, &path, out);
                }
            } else if !matches!(
                name.as_str(),
                "Cargo.lock" | "bun.lock" | "go.sum" | "data.redb"
            ) {
                out.insert(
                    path.strip_prefix(base)
                        .unwrap()
                        .to_string_lossy()
                        .to_string(),
                );
            }
        }
    }

    /// The embedded set must equal the on-disk example, so an example that grows or loses a
    /// file fails here until the template list is updated — the single-source guard.
    #[test]
    fn embedded_set_matches_each_example() {
        for (lang, files, generated) in [
            ("typescript", TS_FILES, &["package.json"][..]),
            ("rust", RS_FILES, &[][..]),
            ("go", GO_FILES, &[][..]),
        ] {
            let embedded: BTreeSet<String> = files
                .iter()
                .map(|(p, _)| p.strip_suffix(".tmpl").unwrap_or(p).to_string())
                .collect();
            assert_eq!(
                embedded,
                on_disk_sources(lang, generated),
                "{lang}: template file set drifted from examples/todo-board/{lang}"
            );
        }
    }

    /// The vendored `templates/<lang>` copy must be byte-identical to the curated
    /// `examples/<lang>` files (same set, same bytes) — so the in-crate copy that ships in
    /// the published tarball can never drift from the real example. Regenerate with
    /// `make sync-templates`.
    #[test]
    fn vendored_templates_match_examples() {
        let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
        for (lang, generated) in [
            ("typescript", &["package.json"][..]),
            ("rust", &[][..]),
            ("go", &[][..]),
        ] {
            let examples = manifest
                .join("..")
                .join("examples")
                .join("todo-board")
                .join(lang);
            let templates = manifest.join("templates").join(lang);

            let mut ex = BTreeSet::new();
            collect(&examples, &examples, &mut ex);
            for g in generated {
                ex.remove(*g);
            }

            // Walk the vendored copy; each file maps to its example by dropping the `.tmpl`
            // the Rust manifests carry. Same mapped set, same bytes — or the copy drifted.
            let mut tpl_raw = BTreeSet::new();
            collect(&templates, &templates, &mut tpl_raw);
            let mut tpl_mapped = BTreeSet::new();
            for t in &tpl_raw {
                let ex_rel = t.strip_suffix(".tmpl").unwrap_or(t).to_string();
                let from_example = std::fs::read(examples.join(&ex_rel)).unwrap_or_else(|_| {
                    panic!("{lang}/{ex_rel}: vendored template has no example — run `make sync-templates`")
                });
                let vendored = std::fs::read(templates.join(t)).unwrap();
                assert_eq!(
                    from_example, vendored,
                    "{lang}/{t}: vendored template drifted from the example — run `make sync-templates`"
                );
                tpl_mapped.insert(ex_rel);
            }
            assert_eq!(
                ex, tpl_mapped,
                "{lang}: templates/{lang} file set drifted from examples/todo-board/{lang} — run `make sync-templates`"
            );
        }
    }

    /// The `weather` custom-bridge scaffold template is vendored — from `examples/weather-api`
    /// (and the `rusm:runtime` guest WIT from `rusm-rs`) into `templates/weather/` — so it ships
    /// in the published `rusm-cli` tarball, where `../../examples/` and `../../crates/` don't
    /// exist. Each vendored file must stay byte-identical to its source, or a scaffolded app
    /// would diverge from the live example. Regenerate with `make sync-templates`.
    #[test]
    fn vendored_weather_template_matches_sources() {
        let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
        let root = manifest.join("..");
        // (vendored under rusm-cli/, canonical source relative to the repo root)
        // `templates/runtime-world.wit` is omitted on purpose: it's a generated rusm:runtime
        // guest world (a TARGETS entry in bridges/assemble-wit.sh), drift-guarded by the
        // `bridge_sync` `world_wit_in_sync` test, not by `make sync-templates`.
        let pairs = [
            (
                "templates/weather/host-main.rs",
                "examples/weather-api/rust/src/main.rs",
            ),
            (
                "templates/weather/bridge.wit",
                "examples/weather-api/rust/bridges/weather/bridge.wit",
            ),
            (
                "templates/weather/host.rs",
                "examples/weather-api/rust/bridges/weather/host.rs",
            ),
            (
                "templates/weather/rust-guest.rs",
                "examples/weather-api/rust/components/api/src/lib.rs",
            ),
            (
                "templates/weather/ts-guest.ts",
                "examples/weather-api/typescript/components/api/index.ts",
            ),
            (
                "templates/weather/go-guest.go",
                "examples/weather-api/go/components/api/main.go",
            ),
        ];
        for (vendored, source) in pairs {
            let v = std::fs::read(manifest.join(vendored)).unwrap_or_else(|_| {
                panic!("missing vendored {vendored} — run `make sync-templates`")
            });
            let s = std::fs::read(root.join(source))
                .unwrap_or_else(|_| panic!("missing source {source}"));
            assert_eq!(
                v, s,
                "{vendored} drifted from {source} — run `make sync-templates`"
            );
        }
    }

    /// No scaffolded manifest may carry a repo-local dependency reference — the standalone
    /// app must depend on the published SDKs, not paths into this tree.
    #[test]
    fn manifests_have_no_repo_local_dep_refs() {
        for lang in [Lang::TypeScript, Lang::Rust, Lang::Go] {
            for (rel, content) in files(lang, "demo") {
                let p = rel.to_string_lossy();
                if p.ends_with("Cargo.toml") || p.ends_with("go.mod") || p.ends_with("package.json")
                {
                    assert!(
                        !content.contains("crates/rusm-rs"),
                        "{p}: leaks rusm-rs path"
                    );
                    assert!(
                        !content.contains("packages/rusm-go =>"),
                        "{p}: leaks rusm-go replace"
                    );
                    assert!(!content.contains("file:"), "{p}: leaks a file: dep");
                }
            }
        }
    }

    /// The published SDK refs the rewrite produces actually land.
    #[test]
    fn manifests_pin_published_sdks() {
        let rs: String = files(Lang::Rust, "demo")
            .into_iter()
            .find(|(p, _)| p.ends_with("components/api/Cargo.toml"))
            .map(|(_, c)| c)
            .unwrap();
        assert!(
            rs.contains(&format!("rusm-rs = \"{SDK_VERSION}\"")),
            "rust pins the published rusm-rs"
        );
        assert!(
            rs.contains("todos = { path"),
            "rust keeps the intra-app todos dep"
        );

        let go: String = files(Lang::Go, "demo")
            .into_iter()
            .find(|(p, _)| p.ends_with("components/api/go.mod"))
            .map(|(_, c)| c)
            .unwrap();
        assert!(
            go.contains(&format!("rusm-go v{SDK_VERSION}")),
            "go pins the published rusm-go"
        );
        assert!(
            go.contains("replace todoboard =>"),
            "go keeps the intra-app replace"
        );
    }
}
