// Code generated by wit-bindgen-go. DO NOT EDIT.

package pg

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "rusm:runtime@0.1.0".

//go:wasmimport rusm:runtime/pg@0.1.0 register-tag
//go:noescape
func wasmimport_RegisterTag(tag0 *uint8, tag1 uint32)

//go:wasmimport rusm:runtime/pg@0.1.0 unregister-tag
//go:noescape
func wasmimport_UnregisterTag(tag0 *uint8, tag1 uint32)

//go:wasmimport rusm:runtime/pg@0.1.0 whereis-tag
//go:noescape
func wasmimport_WhereisTag(tag0 *uint8, tag1 uint32, result *cm.List[Pid])

//go:wasmimport rusm:runtime/pg@0.1.0 kill-tag
//go:noescape
func wasmimport_KillTag(tag0 *uint8, tag1 uint32) (result0 uint32)
