// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package pg represents the imported interface "rusm:runtime/pg@0.1.0".
//
// Process-group tags (Erlang's `pg`) — an **introduced** bridge. A process joins
// a tag,
// many processes may share a tag, and a process may hold many tags; memberships release
// on
// exit (like names). This is RUSM's cross-language pub/sub primitive: subscribe =
// `register-tag`, publish = `whereis-tag` + `send`. `register-tag`/`unregister-tag`
// join/leave **this** process (unprivileged); `kill-tag` terminates a whole group
// and is
// capability-gated by `process-control` (it targets other processes), exactly like
// `kill`.
package pg

import (
	"github.com/archan937/rusm/packages/rusm-go/internal/wit/rusm/runtime/types"
	"go.bytecodealliance.org/cm"
)

// Pid represents the type alias "rusm:runtime/pg@0.1.0#pid".
//
// See [types.Pid] for more information.
type Pid = types.Pid

// RegisterTag represents the imported function "register-tag".
//
// Join this process to `tag`.
//
//	register-tag: func(tag: string)
//
//go:nosplit
func RegisterTag(tag string) {
	tag0, tag1 := cm.LowerString(tag)
	wasmimport_RegisterTag((*uint8)(tag0), (uint32)(tag1))
	return
}

// UnregisterTag represents the imported function "unregister-tag".
//
// Leave a tag this process holds.
//
//	unregister-tag: func(tag: string)
//
//go:nosplit
func UnregisterTag(tag string) {
	tag0, tag1 := cm.LowerString(tag)
	wasmimport_UnregisterTag((*uint8)(tag0), (uint32)(tag1))
	return
}

// WhereisTag represents the imported function "whereis-tag".
//
// Live members of `tag` (empty if unknown).
//
//	whereis-tag: func(tag: string) -> list<pid>
//
//go:nosplit
func WhereisTag(tag string) (result cm.List[Pid]) {
	tag0, tag1 := cm.LowerString(tag)
	wasmimport_WhereisTag((*uint8)(tag0), (uint32)(tag1), &result)
	return
}

// KillTag represents the imported function "kill-tag".
//
// Terminate every live member of `tag`; returns the count. Gated by process-control.
//
//	kill-tag: func(tag: string) -> u32
//
//go:nosplit
func KillTag(tag string) (result uint32) {
	tag0, tag1 := cm.LowerString(tag)
	result0 := wasmimport_KillTag((*uint8)(tag0), (uint32)(tag1))
	result = (uint32)((uint32)(result0))
	return
}
