// GENERATED by `rusm build` — do not edit. Ambient types for the app's custom bridges,
// so a TS guest calls them typed. Regenerated from bridges/ each build.

declare const tenants: {
  data(): string;
};

