//! Per-app **custom-bridge** glue for the js-http-runner — GENERATED by `rusm build` for an
//! app whose TS HTTP/SSE handler calls its own `bridges/<name>/`. **Empty by default**: the
//! prebuilt runner has no custom bridges, so this file is committed empty and the runner
//! compiles unchanged. A per-app js-http-runner build overwrites it with the app's bridge host
//! primitives + JS (the js-runner has its own identical-shaped copy; both come from the one
//! `gen_runner_bridges_gen`, so the *generation* is the single source of truth).
//!
//! Each custom bridge function becomes a typed `__<bridge>__<func>` host primitive that
//! marshals its JS arguments and calls the *typed* WIT binding (no generic dispatcher); the
//! generated [`BRIDGE_JS`] exposes the ergonomic `globalThis.<bridge>` API over those
//! primitives.

use rquickjs::{Ctx, Object};

/// Install each custom bridge's host primitive onto `globals`. Called from `boot_bridge`
/// alongside the built-in `__*` primitives, so the wizer snapshot captures them. A no-op by
/// default.
pub fn register<'js>(_ctx: &Ctx<'js>, _globals: &Object<'js>) {}

/// JS evaluated after the built-in bridge JS to expose each custom bridge's typed API on
/// `globalThis` (over its `__<bridge>__<func>` primitives). Empty by default.
pub const BRIDGE_JS: &str = "";
