//! GENERATED by `rusm build` — do not edit. Typed bindings for the app's custom bridges,
//! from the synthesized `wit/` world. Each bridge's `host.rs` implements these `Host`
//! traits over `rusm_wasm::BridgeHost`. `wasmtime` is the runtime's exact version (pinned
//! in Cargo.toml), so the generated types are identical to the ones the runtime links.
wasmtime::component::bindgen!({
    path: "wit",
    world: "host",
    imports: { default: async },
});
