// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package kv represents the imported interface "rusm:runtime/kv@0.1.0".
//
// Durable key-value storage — a platform bridge **gated by `storage`** (default-deny).
// Bytes in, bytes out, namespaced by `bucket`; backed by an embedded store the node
// owns
// (no external daemon). Each op `err`s with a message if storage is denied or
// unconfigured. The host application owns the store's file; a guest just names buckets
// +
// keys. (`%list` is the WIT keyword-escape — `list` is reserved; wit-bindgen strips
// the
// `%`, so guests call `kv.list()`.)
package kv

import (
	"go.bytecodealliance.org/cm"
)

// Get represents the imported function "get".
//
//	get: func(bucket: string, key: string) -> result<option<list<u8>>, string>
//
//go:nosplit
func Get(bucket string, key string) (result cm.Result[OptionListU8Shape, cm.Option[cm.List[uint8]], string]) {
	bucket0, bucket1 := cm.LowerString(bucket)
	key0, key1 := cm.LowerString(key)
	wasmimport_Get((*uint8)(bucket0), (uint32)(bucket1), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// Set represents the imported function "set".
//
//	set: func(bucket: string, key: string, value: list<u8>) -> result<_, string>
//
//go:nosplit
func Set(bucket string, key string, value cm.List[uint8]) (result cm.Result[string, struct{}, string]) {
	bucket0, bucket1 := cm.LowerString(bucket)
	key0, key1 := cm.LowerString(key)
	value0, value1 := cm.LowerList(value)
	wasmimport_Set((*uint8)(bucket0), (uint32)(bucket1), (*uint8)(key0), (uint32)(key1), (*uint8)(value0), (uint32)(value1), &result)
	return
}

// Delete represents the imported function "delete".
//
//	delete: func(bucket: string, key: string) -> result<bool, string>
//
//go:nosplit
func Delete(bucket string, key string) (result cm.Result[string, bool, string]) {
	bucket0, bucket1 := cm.LowerString(bucket)
	key0, key1 := cm.LowerString(key)
	wasmimport_Delete((*uint8)(bucket0), (uint32)(bucket1), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// Exists represents the imported function "exists".
//
//	exists: func(bucket: string, key: string) -> result<bool, string>
//
//go:nosplit
func Exists(bucket string, key string) (result cm.Result[string, bool, string]) {
	bucket0, bucket1 := cm.LowerString(bucket)
	key0, key1 := cm.LowerString(key)
	wasmimport_Exists((*uint8)(bucket0), (uint32)(bucket1), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// List represents the imported function "list".
//
//	%list: func(bucket: string) -> result<list<string>, string>
//
//go:nosplit
func List(bucket string) (result cm.Result[cm.List[string], cm.List[string], string]) {
	bucket0, bucket1 := cm.LowerString(bucket)
	wasmimport_List((*uint8)(bucket0), (uint32)(bucket1), &result)
	return
}
