// Code generated by wit-bindgen-go. DO NOT EDIT.

package kv

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "rusm:runtime@0.1.0".

//go:wasmimport rusm:runtime/kv@0.1.0 get
//go:noescape
func wasmimport_Get(bucket0 *uint8, bucket1 uint32, key0 *uint8, key1 uint32, result *cm.Result[OptionListU8Shape, cm.Option[cm.List[uint8]], string])

//go:wasmimport rusm:runtime/kv@0.1.0 set
//go:noescape
func wasmimport_Set(bucket0 *uint8, bucket1 uint32, key0 *uint8, key1 uint32, value0 *uint8, value1 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport rusm:runtime/kv@0.1.0 delete
//go:noescape
func wasmimport_Delete(bucket0 *uint8, bucket1 uint32, key0 *uint8, key1 uint32, result *cm.Result[string, bool, string])

//go:wasmimport rusm:runtime/kv@0.1.0 exists
//go:noescape
func wasmimport_Exists(bucket0 *uint8, bucket1 uint32, key0 *uint8, key1 uint32, result *cm.Result[string, bool, string])

//go:wasmimport rusm:runtime/kv@0.1.0 list
//go:noescape
func wasmimport_List(bucket0 *uint8, bucket1 uint32, result *cm.Result[cm.List[string], cm.List[string], string])
