//! Per-app **custom-bridge** glue — GENERATED by `rusm build` for an app that declares its
//! own `bridges/<name>/`. **Empty by default**: the prebuilt runners have no custom bridges,
//! so this file is committed empty and the runners compile unchanged. A per-app js-runner
//! build overwrites it with the app's bridge host primitives + JS. The js-http-runner reuses
//! this same file (via `#[path]`), so both runners share one generated definition.
//!
//! Each custom bridge function becomes a typed `__<bridge>__<func>` host primitive that
//! marshals its JS arguments and calls the *typed* WIT binding (no generic dispatcher); the
//! generated [`BRIDGE_JS`] exposes the ergonomic `globalThis.<bridge>` API over those
//! primitives.

use rquickjs::{Ctx, Object};

/// Install each custom bridge's host primitive onto `globals`. Called from each runner's
/// `boot_bridge` alongside the built-in `__*` primitives, so the wizer snapshot captures
/// them. A no-op by default.
pub fn register<'js>(_ctx: &Ctx<'js>, _globals: &Object<'js>) {}

/// JS evaluated after the built-in bridge JS to expose each custom bridge's typed API on
/// `globalThis` (over its `__<bridge>__<func>` primitives). Empty by default.
pub const BRIDGE_JS: &str = "";
